# _______                              .__ __________               _____.__
# \      \   ___________  _____ _____  |  |\______   \ ____   _____/ ____\__|______   ____
# /   |   \ /  _ \_  __ \/     \\__  \ |  | |    |  _//  _ \ /    \   __\|  \_  __ \_/ __ \
#/    |    (  <_> )  | \/  Y Y  \/ __ \|  |_|    |   (  <_> )   |  \  |  |  ||  | \/\  ___/
#\____|__  /\____/|__|  |__|_|  (____  /____/______  /\____/|___|  /__|  |__||__|    \___  >
#        \/                   \/     \/            \/            \/                      \/

# Разработчиком плагина является NormalWalk_
# Версия плагина: 1.16+
# Если вы нашли баг, просьба сообщить мне - vk.com/normalwalk | t.me/normalwalk
# Предложить идею по доработке плагина вы можете на сайте, с которого скачали ресурс

# Права плагина:
# normalbonfire.give - права на выдачу костра
# normalbonfire.reload - права на перезагрузку конфигурации плагина

# Команды плагина:
# /normalbonfire give (ник игрока) (кол-во) - выдать костер игроку
# /normalbonfire reload - перезагрузить конфигурацию плагина


# Конфигурация для плагина NormalBonfire
effect:
  enabled: true # Включение/отключение эффекта
  type: FAST_DIGGING # Тип эффекта (https://helpch.at/docs/1.16.5/org/bukkit/potion/PotionEffectType.html)
  amplifier: 1 # Уровень эффекта (1 = 2 уровень)

regeneration:
  health: 1 # Количество регенерируемого здоровья (1 = 1 сердце)

damage:
  enabled: true # Включение/отключение урона мобам
  amount: 2 # Урон по мобам

radius: 15 # Радиус действия костра
custom-name: "&3Уникальный костёр"

message:
  succesfull-give: "&3&lПЛАГИН: &fВам был выдан костер!"
  no-permission: "&3&lПЛАГИН: &fУ вас нет прав на выполнение этой команды!"
  no-player: "&3&lПЛАГИН: &fИгрок не найден."
  error-format: "&3&lПЛАГИН: &fНекорректный формат команды."
  reload: "&3&lПЛАГИН: &fКонфигурация успешно перезагружена."
  no-permission-reload: "&3&lПЛАГИН: &fУ вас нет прав на перезагрузку конфига!"
  too-close: "&3&lПЛАГИН: &fВ радиусе &n15 блоков&r&f уже стоит уникальный костёр!" # Пытался реализовать функцию, чтобы нельзя было задевать чужой регион, но опустил руки. Но, я заметил, что костёр нельзя поставить если рядом есть регион,то есть если в радиусе костра есть регион, то он не поставит.
